description: "Train Graph Autoencoder"

# Data
data_folder: "data\\transformed_subgraphs_08032025_2"
real_data_folder: "data_combined_real_world"

# Model
model_module: "GraphAutoencoder"

# Training
input_dim: 4
hidden_dims: [256, 128, 64, 32, 16]
latent_dim: 8
activation: "relu"
dropout_rate: 0.0
learning_rate: 0.001
weight_decay: 0.00005
batch_size: 1
epochs: 100
patience: 10
hp_search: false
hp_search_n_trials: 50
job_name: "first run"
criterion_name: MSELoss
wandb: False