description: "HPO Best Trial Config - GCN with WeightedBCELoss"
job_name: "hpo_best_trial_gcn"

# HPO Metadata
_hpo_metadata:
  best_f1_score: 0.9367  
  best_trial: 5  
  completed_trials: 80
  csv_file: "hpo_results.csv"
  experiment_id: "hpo_20250614_012009"
  total_trials: 80

# Data Configuration
dataset_names: ["train", "validation", "test"]
folder_names: 
  - "data\\split_datasets\\train"
  - "data\\split_datasets\\validation"
  - "data\\split_datasets\\test"

# Model Configuration
model_module: "AdvancedMLP"
model_kwargs:
  # GCN Configuration
  gnn_type: "GCN"
  gnn_layers: 5
  gnn_hidden_dim: 113  # gnn_hidden_dim_multiple * 9 (assuming base 9)
  
  # MLP Configuration
  use_node_mlp: true
  use_edge_mlp: true
  node_hidden_dims: [352, 256]  # 2 layers as specified
  edge_hidden_dims: [192, 352]  # 2 layers as specified
  
  # General Configuration
  activation: "gelu"
  dropout_rate: 0.060691248558227884
  use_batch_norm: true
  use_residual: false
  use_skip_connections: true
  pooling: "max"
  
  # Switch Head Configuration
  switch_head_type: "mlp"
  switch_head_layers: 2
  
  # Physics Configuration
  use_gated_mp: true
  use_phyr: true
  phyr_k_ratio: 0.18569452544519777
  
  # Loss and normalization
  loss_scaling_strategy: "fixed"
  normalization_type: "injection_scale"

# Training Configuration
learning_rate: 0.008910671508622504
weight_decay: 1.8285523498725977e-06
batch_size: 128
epochs: 100
patience: 15

# Physics Loss Weights
lambda_phy_loss: 0.519874529197544
lambda_connectivity: 0.477593421142367
lambda_radiality: 0.009166025938972713
lambda_mask: 0.011670683878208651

# Output configuration
output_type: "binary"
num_classes: 2

# Data Loading Configuration
dataset_type: "default"
batching_type: "dynamic"
max_nodes: 5000
max_edges: 5000
train_ratio: 0.85
seed: 42
num_workers: 0

# Criterion
criterion_name: "WeightedBCELoss"

# Evaluation
wandb_project: "GCN_HPO"
wandb: false