data_folder: r"C:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\data\1739737645.4646165"
real_data_folder: r"C:\Users\denni\Documents\thesis_dnr_gnn_dev\model_search\data\data_combined_real_world"  
project: "graph-autoencoder"
save_dir: "models/"
max_epochs: 100

trainer_params:  
  accelerator: "auto"
  devices: auto

callbacks_config: 
  model_checkpoint:
    monitor: "val_loss"
    mode: "min"
    save_top_k: 3
    filename: "{epoch}-{val_loss:.2f}"
  early_stopping:
    monitor: "val_loss"
    patience: 10
    mode: "min"
  lr_monitor:
    logging_interval: "epoch"

train_ratio: 0.7
val_ratio: 0.15
test_ratio: 0.15
batch_size: 1

input_dim: 4
hidden_dims: [64, 32, 16]
latent_dim: 8
learning_rate: 0.001
weight_decay: 1e-5
dropout_rate: 0.0
loss_fn: "mse"       
optimizer: "adam"    
scheduler: null      
activation: "prelu"  #"relu", "leaky_relu", "elu", "selu", "prelu"

hp_search: true
hp_search_n_trials: 50
