description: "GCN model with hyperparameter optimization"
job_name: "best-GCN"

# Data Configuration
dataset_names: ["train", "validation", "test"]
folder_names:
  - data\\split_datasets\\train
  - data\\split_datasets\\validation
  - data\\split_datasets\\test
# -  data\\source_datasets\\test_val_real__range-30-150_nTest-10_nVal-10_2732025_32\\test
# -  data\\source_datasets\\test_val_real__range-30-150_nTest-10_nVal-10_2732025_32\\test
# -  data\\source_datasets\\test_val_real__range-30-150_nTest-10_nVal-10_2732025_32\\test
dataset_type: "cvx"
batching_type: "dynamic"
max_nodes: 20000
max_edges: 50000
batch_size: 8
train_ratio: 0.85
seed: 0
num_workers: 0

# Training Configuration
learning_rate: 0.00035760499745340354
weight_decay: 3.1083921460064515e-05
epochs: 200
patience: 20
criterion_name: "FocalLoss"

# Physics Loss Configuration (used in training loop)
lambda_phy_loss: 0.7459167213752221
lambda_mask: 0.05936503481046906
lambda_connectivity: 0.0022114859650502207
lambda_radiality: 0.001644915684713298
loss_scaling_strategy: "fixed"
normalization_type: "adaptive"

# Hyperparameter Search
hp_search: false
hp_search_n_trials: 50

# Model Configuration
model_module: "cvx"
model_kwargs:
  # Output Configuration
  output_type: "binary"
  num_classes: 2
  
  # GNN Configuration
  gnn_type: "GCN"
  gnn_layers: 1
  gnn_hidden_dim: 360  # Fixed from gnn_hidden_dim_multiple
  gin_eps: 0.0  # Added (required parameter)
  gat_heads: 4  # Added (default value)
  gat_dropout: 0.1  # Added (default value)

  # MLP Configuration
  use_node_mlp: true
  node_hidden_dims: [256, 512, 512]
  use_edge_mlp: true
  edge_hidden_dims: [256, 512]

  # General Configuration
  activation: "leaky_relu"
  dropout_rate: 0.0
  use_batch_norm: true
  use_residual: true
  use_skip_connections: true
  pooling: "add"

  # Switch Head Configuration
  switch_head_type: "mlp"
  switch_head_layers: 3
  switch_attention_heads: 4  # Added

  # Physics Configuration
  use_gated_mp: true
  use_phyr: false
  enforce_radiality: false  # Added

# Logging
wandb: true
wandb_project: "GIN_HPO"