activation: prelu
batch_size: 4
config: null
criterion_name: MSELoss
data_folder: null
dropout_rate: 0.0
epochs: 100
hidden_dims:
- 64
- 32
- 16
hp_search: false
hp_search_n_trials: 50
input_dim: null
job_name: default_job
latent_dim: 8
learning_rate: 0.001
model_module: first_model
patience: 10
real_data_folder: null
wandb: false
weight_decay: 1.0e-05
