# ====================================================================
# hpo-GIN-stage1.yaml
# Stage 1: Architecture Search (10 dimensions)
# ====================================================================

# Basic model configuration
model_module: "AdvancedMLP"
dataset_names: ["train", "validation", "test"]
folder_names:
  - "data\\split_datasets\\train"
  - "data\\split_datasets\\validation"
  - "data\\split_datasets\\test"
dataset_type: "default"
batching_type: "dynamic"
batch_size: 128
max_nodes: 10000
max_edges: 50000
num_workers: 0
criterion_name: "WeightedBCELoss"


# Fixed parameters for Stage 1
fixed_params:
  # Core GNN settings
  gnn_type: "GIN"  
  use_node_mlp: true
  use_edge_mlp: true
  
  # Data settings
  batch_size: 128
  max_nodes: 10000
  max_edges: 50000
  train_ratio: 0.85
  num_workers: 0
  seed: 42
  
  # Training settings
  epochs: 200
  patience: 100
  learning_rate: 2.5e-05
  weight_decay: 0.00005

  # Fixed architecture choices for Stage 1
  activation: "relu"
  use_batch_norm: true
  use_residual: false
  normalization_type: "simple"
  use_gated_mp: false
  use_phyr: false
  pooling: "add"
  
  # Output settings 
  output_type: "binary"
  num_classes: 2  
  wandb_project: "GIN_HPO_Stage1"

# Stage 1 Search Space - 10 dimensions for architecture
search_space:
  # 1. GNN layers
  gnn_layers:
    search_type: "int"
    min: 1
    max: 4

  # 2. GNN hidden dimension
  gnn_hidden_dim:
    search_type: "categorical"
    choices: [64, 128, 192, 256, 320, 384, 512]

  # 3. GIN epsilon 
  gin_eps:
    search_type: "float"
    min: 0.0
    max: 0.1

  # 6. Node MLP layers
  node_mlp_layers:
    search_type: "int"
    min: 1
    max: 3

  # 7. Node MLP dimension
  node_mlp_dim:
    search_type: "categorical"
    choices: [64, 128, 256, 384,512]

  # 8. Edge MLP layers
  edge_mlp_layers:
    search_type: "int"
    min: 1
    max: 3

  # 9. Edge MLP dimension
  edge_mlp_dim:
    search_type: "categorical"
    choices: [32, 64, 128, 256,384,512]

  # 10. Switch head type
  switch_head_type:
    search_type: "categorical"
    choices: ["mlp", "attention", "graph_attention"]

  switch_head_layers:
    search_type: "int"
    min: 1
    max: 5
  