description: "Stage 1 HPO for GAT: Architecture search"
job_name: "GAT-stage1-architecture-search"

# --- Data Configuration ---
dataset_names: ["train", "validation", "test"]
folder_names: 
  - "/vast.mnt/home/20174047/gnn-dnr/data/split_datasets/train"
  - "/vast.mnt/home/20174047/gnn-dnr/data/split_datasets/validation"
  - "/vast.mnt/home/20174047/gnn-dnr/data/split_datasets/test"
dataset_type: "default"
batching_type: "dynamic"
max_nodes: 20000
max_edges: 50000
train_ratio: 0.85
seed: 0
num_workers: 0
wandb: false

# --- Model Configuration ---
model_module: "AdvancedMLP"

# --- Fixed Parameters for Stage 1 ---
fixed_params:
  output_type: "multiclass"
  num_classes: 2
  gnn_type: "GAT"
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 100
  patience: 15
  criterion_name: "FocalLoss"
  lambda_phy_loss: 0.5
  lambda_mask: 0.01
  lambda_connectivity: 0.01
  lambda_radiality: 0.01
  loss_scaling_strategy: "fixed"
  normalization_type: "paper_based"
  use_batch_norm: true
  use_phyr: false
  enforce_radiality: false
  gin_eps: 0.0
  gat_dropout: 0.0 

# --- STAGE 1: ARCHITECTURE SEARCH SPACE ---
search_space:
  # General Architecture Choices
  activation:
    search_type: "categorical"
    choices: ["relu", "leaky_relu", "elu"]
  use_residual:
    search_type: "categorical"
    choices: [true, false]
  use_skip_connections:
    search_type: "categorical"
    choices: [true, false]
  use_gated_mp:
    search_type: "categorical"
    choices: [true, false]

  # GNN Architecture
  gnn_layers:
    search_type: "int"
    min: 1
    max: 4
  gnn_hidden_dim:
    search_type: "categorical"
    choices: [64, 128, 192, 256, 384, 512] 
  gat_heads:
    search_type: "categorical"
    choices: [1, 2, 4, 8]

  # Node MLP Architecture (dim=0 means layer is not used)
  node_hidden_dim_0:
    search_type: "categorical"
    choices: [0,32, 64, 128, 256, 512]
  node_hidden_dim_1:
    search_type: "categorical"
    choices: [0, 64, 128, 256, 512]
  node_hidden_dim_2:
    search_type: "categorical"
    choices: [0, 64, 128, 256]
  
  # Edge MLP Architecture (dim=0 means layer is not used)
  edge_hidden_dim_0:
    search_type: "categorical"
    choices: [0,32, 64, 128, 256, 512]
  edge_hidden_dim_1:
    search_type: "categorical"
    choices: [0, 64, 128, 256, 512]
  edge_hidden_dim_2:
    search_type: "categorical"
    choices: [0, 64, 128, 256]
  
  # Switch Head Architecture
  switch_head_type:
    search_type: "categorical"
    choices: ["mlp", "attention", "graph_attention"]

  switch_head_layers:
    search_type: "int"
    min: 1
    max: 5

  switch_attention_heads:
    search_type: "categorical"
    choices: [1, 2, 4, 8] 