description: "Stage 2 HPO for GAT: Hyperparameter tuning with best architecture from Stage 1"
job_name: "GAT-stage2-hyperparameter-tuning"

# --- Data Configuration ---
dataset_names: ["train", "validation", "test"]
folder_names: 
  - "/vast.mnt/home/20174047/gnn-dnr/data/split_datasets/train"
  - "/vast.mnt/home/20174047/gnn-dnr/data/split_datasets/validation"
  - "/vast.mnt/home/20174047/gnn-dnr/data/split_datasets/test"
dataset_type: "default"
batching_type: "dynamic"
max_nodes: 20000
max_edges: 50000
train_ratio: 0.85
seed: 44
num_workers: 0
wandb: false
batch_size: 128
# --- Model Configuration ---
model_module: "AdvancedMLP"

# --- STAGE 2: Fixed Parameters (Best Architecture from Stage 1) ---
fixed_params:
  batch_size: 128
  # Output Configuration
  output_type: "multiclass"
  num_classes: 2
  
  # Best GAT Architecture from Stage 1 (Trial 175)
  gnn_type: "GAT"
  gnn_layers: 2
  gat_heads: 4
  gnn_hidden_dim: 64
  activation: "leaky_relu"
  
  # Best MLP Architecture from Stage 1 (Trial 175)
  node_hidden_dims: [0, 256,512]
  edge_hidden_dims: [128, 128, 128]
  
  # Best Switch Head Architecture from Stage 1 (Trial 175)
  switch_head_type: "mlp"
  switch_head_layers: 4
  switch_attention_heads: 0
  
  # Best General Configuration from Stage 1 (Trial 175)
  use_residual: false
  use_skip_connections: true
  use_gated_mp: true
  
  # Default GIN params
  gin_eps: 0.0

  # Training Configuration (partially fixed)
  epochs: 200
  patience: 25
  criterion_name: "FocalLoss"

# --- STAGE 2: HYPERPARAMETER TUNING SEARCH SPACE ---
search_space:
  use_batch_norm:
    search_type: "categorical"
    choices: [true, false]
  criterion_name:
    search_type: "categorical"
    choices: ["CrossEntropyLoss", "FocalLoss", "WeightedBCELoss"]
  # Training Hyperparameters
  learning_rate:
    search_type: "float"
    min: 0.0001
    max: 0.01
    log: true
  weight_decay:
    search_type: "float"
    min: 1.0e-6
    max: 1.0e-3
    log: true
  dropout_rate: # General dropout
    search_type: "float"
    min: 0.0
    max: 0.5
  
  # GAT-specific hyperparameters
  gat_dropout:
    search_type: "float"
    min: 0.0
    max: 0.5

  # Physics Loss Hyperparameters
  lambda_phy_loss:
    search_type: "float"
    min: 0.1
    max: 10.0
    log: true
  lambda_mask:
    search_type: "float"
    min: 0.001
    max: 10
    log: true
  lambda_connectivity:
    search_type: "float"
    min: 0.001
    max: 10
    log: true
  lambda_radiality:
    search_type: "float"
    min: 0.001
    max: 10
    log: true

  # Strategy Hyperparameters
  loss_scaling_strategy:
    search_type: "categorical"
    choices: ["fixed", "adaptive_ratio", "adaptive_magnitude"]
  normalization_type:
    search_type: "categorical"
    choices: ["adaptive", "simple", "injection_scale", "per_node", "paper_based"]
