
# ====================================================================
# hpo-GCN-phase1.yaml
# Phase 1: Architecture Search (10 dimensions)
# ====================================================================

# Basic model configuration
model_module: "AdvancedMLP"
dataset_names: ["train", "validation", "test"]
folder_names:
  - "data\\split_datasets\\train"
  - "data\\split_datasets\\validation"
  - "data\\split_datasets\\test"
dataset_type: "default"
batching_type: "dynamic"

# Fixed parameters for Phase 1
fixed_params:
  # Core GNN settings
  gnn_type: "GCN"  
  use_node_mlp: true
  use_edge_mlp: true
  
  # Data settings
  batch_size: 128
  max_nodes: 1000
  max_edges: 5000
  train_ratio: 0.85
  num_workers: 0
  seed: 42
  
  # Training settings
  epochs: 200
  patience: 15
  learning_rate: 0.000025  # 1e-4 * 32/batch_size = 1e-4 * 32/128
  
  # Fixed architecture choices for Phase 1
  activation: "relu"
  use_batch_norm: true
  use_residual: false
  criterion_name: "WeightedBCELoss"
  normalization_type: "simple"
  use_gated_mp: false
  use_phyr: false
  pooling: "add"
  
  # Output settings 
  output_type: "multi_class"
  num_classes: 2
  wandb_project: "GCN_HPO_Phase1"

# Phase 1 Search Space - 10 dimensions 
search_space:
  # 1. GNN layers
  gnn_layers:
    search_type: "int"
    min: 1
    max: 4
    
  # 2. GNN hidden dimension
  gnn_hidden_dim:
    search_type: "categorical"
    choices: [64, 128, 256, 384, 512]
    
  # 3. Dropout rate
  dropout_rate:
    search_type: "float"
    min: 0.0
    max: 0.5
    
  # 4. Number of node MLP layers
  node_mlp_layers:
    search_type: "int"
    min: 1
    max: 3
    
  # 5. Node MLP hidden dimension
  node_mlp_dim:
    search_type: "categorical"
    choices: [64, 128, 256, 384]
    
  # 6. Number of edge MLP layers
  edge_mlp_layers:
    search_type: "int"
    min: 1
    max: 3
    
  # 7. Edge MLP hidden dimension
  edge_mlp_dim:
    search_type: "categorical"
    choices: [32, 64, 128, 256]
    
  # 8. Switch head type
  switch_head_type:
    search_type: "categorical"
    choices: ["mlp", "attention", "graph_attention"]
    
  # 9. Switch head layers
  switch_head_layers:
    search_type: "int"
    min: 1
    max: 5
    
  # 10. Use skip connections
  use_skip_connections:
    search_type: "categorical"
    choices: [true, false]

# Phase 2 Parameters (for fine-tuning best architecture):
# learning_rate: [1e-5, 1e-3] (log scale)
# weight_decay: [1e-6, 1e-3] (log scale)  
# activation: ["relu", "gelu", "elu", "leaky_relu"]
# use_batch_norm: [true, false]
# use_residual: [true, false]
# criterion_name: ["CrossEntropyLoss", "WeightedBCELoss", "FocalLoss"]
# normalization_type: ["simple", "injection_scale", "adaptive"]
# loss_scaling_strategy: ["fixed", "adaptive_ratio", "adaptive_magnitude"]