_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 9
                - 35
                - 53
                - 55
                - 77
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 35
                - 53
                - 55
                - 77
                - 103
                - 106
            "3":
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.5
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
